<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Numero Documento',
'Fecha de Registro',
'Fecha de Creacion',
'Tipo de CDP',
'Estado',
'Dependencia',
'Dependencia Descripcion',
'Rubro',
'Descripcion',
'Fuente',
'Recurso',
'Sit',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Saldo por Comprometer',
'Objeto',
'Solicitud CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Reintegros' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Numero Documento' => array( 'import_field' ),
'Fecha de Registro' => array( 'import_field1' ),
'Fecha de Creacion' => array( 'import_field2' ),
'Tipo de CDP' => array( 'import_field3' ),
'Estado' => array( 'import_field4' ),
'Dependencia' => array( 'import_field5' ),
'Dependencia Descripcion' => array( 'import_field6' ),
'Rubro' => array( 'import_field7' ),
'Descripcion' => array( 'import_field8' ),
'Fuente' => array( 'import_field9' ),
'Recurso' => array( 'import_field10' ),
'Sit' => array( 'import_field11' ),
'Valor Inicial' => array( 'import_field12' ),
'Valor Operaciones' => array( 'import_field13' ),
'Valor Actual' => array( 'import_field14' ),
'Saldo por Comprometer' => array( 'import_field15' ),
'Objeto' => array( 'import_field16' ),
'Solicitud CDP' => array( 'import_field17' ),
'Compromisos' => array( 'import_field18' ),
'Cuentas por Pagar' => array( 'import_field19' ),
'Obligaciones' => array( 'import_field20' ),
'Ordenes de Pago' => array( 'import_field21' ),
'Reintegros' => array( 'import_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Numero Documento',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Fecha de Registro',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Fecha de Creacion',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Tipo de CDP',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Dependencia',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Dependencia Descripcion',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Rubro',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Descripcion',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Fuente',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Recurso',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Sit',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Valor Inicial',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Valor Operaciones',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Valor Actual',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Saldo por Comprometer',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Objeto',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Solicitud CDP',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Compromisos',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Cuentas por Pagar',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Obligaciones',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'Ordenes de Pago',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'Reintegros',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>