<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'active',
'covid_fecha',
'covid_sn',
'ctrl',
'ctrl_contacto',
'ctrl_pedidoalmacen',
'estado_vinculacion_mincit',
'ext_security_id',
'global_rol',
'global_rol_almacen',
'global_rol_cej',
'global_rol_ci',
'global_rol_ciudadano',
'global_rol_ciudadano_dep',
'global_rol_comacc',
'global_rol_cont',
'global_rol_contratos',
'global_rol_cpanel',
'global_rol_dashboard',
'global_rol_gestion',
'global_rol_gh',
'global_rol_hojar',
'global_rol_inmuebles',
'global_rol_jc3',
'global_rol_me',
'global_rol_procjur',
'global_rol_sid',
'global_rol_siis',
'global_rol_sipi',
'global_rol_th',
'global_rol_zf',
'globla_rol_ct',
'groupid',
'habilita_almacen',
'id_fk',
'idusrglobal',
'Password',
'phone',
'phone1',
'reset_date',
'reset_token',
'sys_anio',
'sys_date',
'sys_disabledate_usr',
'sys_expiration_usr',
'sys_ntries_usr',
'sys_registrationdate_usr',
'sys_time',
'sys_upd_fecha',
'sys_upd_time',
'sys_upd_user',
'sys_update_family_info',
'sys_update_info',
'sys_user',
'upd_date',
'user_dep',
'Username',
'userpic',
'usr_cargo',
'usr_datebirth',
'usr_dep',
'usr_dep_sup',
'usr_dependencia',
'usr_directivo',
'usr_edl',
'usr_email',
'usr_emergencia',
'usr_entidad',
'usr_extension',
'usr_firma',
'usr_firma_b',
'usr_hojaruta',
'usr_image',
'usr_inicial',
'usr_jefe',
'usr_lname',
'usr_minequipo_grupo',
'usr_minequipo_lider',
'usr_name',
'usr_nombresfull',
'usr_not',
'usr_not_msj',
'usr_personalid',
'usr_piso',
'usr_rdnkey',
'usr_regpago',
'usr_sessini',
'usr_status',
'usr_status_nomina',
'usr_status_sol',
'usr_type_vinc',
'usr_type_vinculacion',
'usr_update_almacen',
'vacuna_a_fecha',
'vacuna_autoriza',
'vacuna_autoriza_email',
'vacuna_b_fecha',
'vacuna_b_fechaprog',
'vacuna_c_fecha',
'vacuna_consentimiento_sn',
'vacuna_dosis',
'vacuna_etapa',
'vacuna_interes',
'vacuna_nombre',
'vacuna_obs',
'vacuna_sn' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'active' => array( 'integrated_edit_field' ),
'covid_fecha' => array( 'integrated_edit_field1' ),
'covid_sn' => array( 'integrated_edit_field2' ),
'ctrl' => array( 'integrated_edit_field3' ),
'ctrl_contacto' => array( 'integrated_edit_field4' ),
'ctrl_pedidoalmacen' => array( 'integrated_edit_field5' ),
'estado_vinculacion_mincit' => array( 'integrated_edit_field6' ),
'ext_security_id' => array( 'integrated_edit_field7' ),
'global_rol' => array( 'integrated_edit_field8' ),
'global_rol_almacen' => array( 'integrated_edit_field9' ),
'global_rol_cej' => array( 'integrated_edit_field10' ),
'global_rol_ci' => array( 'integrated_edit_field11' ),
'global_rol_ciudadano' => array( 'integrated_edit_field12' ),
'global_rol_ciudadano_dep' => array( 'integrated_edit_field13' ),
'global_rol_comacc' => array( 'integrated_edit_field14' ),
'global_rol_cont' => array( 'integrated_edit_field15' ),
'global_rol_contratos' => array( 'integrated_edit_field16' ),
'global_rol_cpanel' => array( 'integrated_edit_field17' ),
'global_rol_dashboard' => array( 'integrated_edit_field18' ),
'global_rol_gestion' => array( 'integrated_edit_field19' ),
'global_rol_gh' => array( 'integrated_edit_field20' ),
'global_rol_hojar' => array( 'integrated_edit_field21' ),
'global_rol_inmuebles' => array( 'integrated_edit_field22' ),
'global_rol_jc3' => array( 'integrated_edit_field23' ),
'global_rol_me' => array( 'integrated_edit_field24' ),
'global_rol_procjur' => array( 'integrated_edit_field25' ),
'global_rol_sid' => array( 'integrated_edit_field26' ),
'global_rol_siis' => array( 'integrated_edit_field27' ),
'global_rol_sipi' => array( 'integrated_edit_field28' ),
'global_rol_th' => array( 'integrated_edit_field29' ),
'global_rol_zf' => array( 'integrated_edit_field30' ),
'globla_rol_ct' => array( 'integrated_edit_field31' ),
'groupid' => array( 'integrated_edit_field32' ),
'habilita_almacen' => array( 'integrated_edit_field33' ),
'id_fk' => array( 'integrated_edit_field34' ),
'idusrglobal' => array( 'integrated_edit_field35' ),
'Password' => array( 'integrated_edit_field36' ),
'phone' => array( 'integrated_edit_field37' ),
'phone1' => array( 'integrated_edit_field38' ),
'reset_date' => array( 'integrated_edit_field39' ),
'reset_token' => array( 'integrated_edit_field40' ),
'sys_anio' => array( 'integrated_edit_field41' ),
'sys_date' => array( 'integrated_edit_field42' ),
'sys_disabledate_usr' => array( 'integrated_edit_field43' ),
'sys_expiration_usr' => array( 'integrated_edit_field44' ),
'sys_ntries_usr' => array( 'integrated_edit_field45' ),
'sys_registrationdate_usr' => array( 'integrated_edit_field46' ),
'sys_time' => array( 'integrated_edit_field47' ),
'sys_upd_fecha' => array( 'integrated_edit_field48' ),
'sys_upd_time' => array( 'integrated_edit_field49' ),
'sys_upd_user' => array( 'integrated_edit_field50' ),
'sys_update_family_info' => array( 'integrated_edit_field51' ),
'sys_update_info' => array( 'integrated_edit_field52' ),
'sys_user' => array( 'integrated_edit_field53' ),
'upd_date' => array( 'integrated_edit_field54' ),
'user_dep' => array( 'integrated_edit_field55' ),
'Username' => array( 'integrated_edit_field56' ),
'userpic' => array( 'integrated_edit_field57' ),
'usr_cargo' => array( 'integrated_edit_field58' ),
'usr_datebirth' => array( 'integrated_edit_field59' ),
'usr_dep' => array( 'integrated_edit_field60' ),
'usr_dep_sup' => array( 'integrated_edit_field61' ),
'usr_dependencia' => array( 'integrated_edit_field62' ),
'usr_directivo' => array( 'integrated_edit_field63' ),
'usr_edl' => array( 'integrated_edit_field64' ),
'usr_email' => array( 'integrated_edit_field65' ),
'usr_emergencia' => array( 'integrated_edit_field66' ),
'usr_entidad' => array( 'integrated_edit_field67' ),
'usr_extension' => array( 'integrated_edit_field68' ),
'usr_firma' => array( 'integrated_edit_field69' ),
'usr_firma_b' => array( 'integrated_edit_field70' ),
'usr_hojaruta' => array( 'integrated_edit_field71' ),
'usr_image' => array( 'integrated_edit_field72' ),
'usr_inicial' => array( 'integrated_edit_field73' ),
'usr_jefe' => array( 'integrated_edit_field74' ),
'usr_lname' => array( 'integrated_edit_field75' ),
'usr_minequipo_grupo' => array( 'integrated_edit_field76' ),
'usr_minequipo_lider' => array( 'integrated_edit_field77' ),
'usr_name' => array( 'integrated_edit_field78' ),
'usr_nombresfull' => array( 'integrated_edit_field79' ),
'usr_not' => array( 'integrated_edit_field80' ),
'usr_not_msj' => array( 'integrated_edit_field81' ),
'usr_personalid' => array( 'integrated_edit_field82' ),
'usr_piso' => array( 'integrated_edit_field83' ),
'usr_rdnkey' => array( 'integrated_edit_field84' ),
'usr_regpago' => array( 'integrated_edit_field85' ),
'usr_sessini' => array( 'integrated_edit_field86' ),
'usr_status' => array( 'integrated_edit_field87' ),
'usr_status_nomina' => array( 'integrated_edit_field88' ),
'usr_status_sol' => array( 'integrated_edit_field89' ),
'usr_type_vinc' => array( 'integrated_edit_field90' ),
'usr_type_vinculacion' => array( 'integrated_edit_field91' ),
'usr_update_almacen' => array( 'integrated_edit_field92' ),
'vacuna_a_fecha' => array( 'integrated_edit_field93' ),
'vacuna_autoriza' => array( 'integrated_edit_field94' ),
'vacuna_autoriza_email' => array( 'integrated_edit_field95' ),
'vacuna_b_fecha' => array( 'integrated_edit_field96' ),
'vacuna_b_fechaprog' => array( 'integrated_edit_field97' ),
'vacuna_c_fecha' => array( 'integrated_edit_field98' ),
'vacuna_consentimiento_sn' => array( 'integrated_edit_field99' ),
'vacuna_dosis' => array( 'integrated_edit_field100' ),
'vacuna_etapa' => array( 'integrated_edit_field101' ),
'vacuna_interes' => array( 'integrated_edit_field102' ),
'vacuna_nombre' => array( 'integrated_edit_field103' ),
'vacuna_obs' => array( 'integrated_edit_field104' ),
'vacuna_sn' => array( 'integrated_edit_field105' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'top' => array( 'view_header' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'view_header' => 'top',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field31' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field34' => 'grid',
'integrated_edit_field35' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field37' => 'grid',
'integrated_edit_field38' => 'grid',
'integrated_edit_field39' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field47' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field52' => 'grid',
'integrated_edit_field53' => 'grid',
'integrated_edit_field54' => 'grid',
'integrated_edit_field55' => 'grid',
'integrated_edit_field56' => 'grid',
'integrated_edit_field57' => 'grid',
'integrated_edit_field58' => 'grid',
'integrated_edit_field59' => 'grid',
'integrated_edit_field60' => 'grid',
'integrated_edit_field61' => 'grid',
'integrated_edit_field62' => 'grid',
'integrated_edit_field63' => 'grid',
'integrated_edit_field64' => 'grid',
'integrated_edit_field65' => 'grid',
'integrated_edit_field66' => 'grid',
'integrated_edit_field67' => 'grid',
'integrated_edit_field68' => 'grid',
'integrated_edit_field69' => 'grid',
'integrated_edit_field70' => 'grid',
'integrated_edit_field71' => 'grid',
'integrated_edit_field72' => 'grid',
'integrated_edit_field73' => 'grid',
'integrated_edit_field74' => 'grid',
'integrated_edit_field75' => 'grid',
'integrated_edit_field76' => 'grid',
'integrated_edit_field77' => 'grid',
'integrated_edit_field78' => 'grid',
'integrated_edit_field79' => 'grid',
'integrated_edit_field80' => 'grid',
'integrated_edit_field81' => 'grid',
'integrated_edit_field82' => 'grid',
'integrated_edit_field83' => 'grid',
'integrated_edit_field84' => 'grid',
'integrated_edit_field85' => 'grid',
'integrated_edit_field86' => 'grid',
'integrated_edit_field87' => 'grid',
'integrated_edit_field88' => 'grid',
'integrated_edit_field89' => 'grid',
'integrated_edit_field90' => 'grid',
'integrated_edit_field91' => 'grid',
'integrated_edit_field92' => 'grid',
'integrated_edit_field93' => 'grid',
'integrated_edit_field94' => 'grid',
'integrated_edit_field95' => 'grid',
'integrated_edit_field96' => 'grid',
'integrated_edit_field97' => 'grid',
'integrated_edit_field98' => 'grid',
'integrated_edit_field99' => 'grid',
'integrated_edit_field100' => 'grid',
'integrated_edit_field101' => 'grid',
'integrated_edit_field102' => 'grid',
'integrated_edit_field103' => 'grid',
'integrated_edit_field104' => 'grid',
'integrated_edit_field105' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field82' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field83' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field86' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field87' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field88' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field89' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field90' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field91' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field92' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field93' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field94' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field95' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field96' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field97' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field98' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field99' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field100' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field101' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field102' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field103' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field104' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field105' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'field' => 'active',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'covid_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'covid_sn',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'ctrl',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'ctrl_contacto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'ctrl_pedidoalmacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'estado_vinculacion_mincit',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'ext_security_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'global_rol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'global_rol_almacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'global_rol_cej',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'global_rol_ci',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'global_rol_ciudadano',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'global_rol_ciudadano_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'global_rol_comacc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'global_rol_cont',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'global_rol_contratos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'global_rol_cpanel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'global_rol_dashboard',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'global_rol_gestion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'global_rol_gh',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'global_rol_hojar',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'global_rol_inmuebles',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'global_rol_jc3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'global_rol_me',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'global_rol_procjur',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'global_rol_sid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'global_rol_siis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'global_rol_sipi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'global_rol_th',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'global_rol_zf',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'globla_rol_ct',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'groupid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'habilita_almacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'idusrglobal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'Password',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'phone',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'phone1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'reset_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'reset_token',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'sys_anio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'sys_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'sys_disabledate_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'sys_expiration_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'sys_ntries_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'sys_registrationdate_usr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'sys_time',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'sys_upd_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'sys_upd_time',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'sys_upd_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'sys_update_family_info',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'sys_update_info',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field53' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field54' => array( 'field' => 'upd_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'user_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field56' => array( 'field' => 'Username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field57' => array( 'field' => 'userpic',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field58' => array( 'field' => 'usr_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field59' => array( 'field' => 'usr_datebirth',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field60' => array( 'field' => 'usr_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field61' => array( 'field' => 'usr_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field62' => array( 'field' => 'usr_dependencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field63' => array( 'field' => 'usr_directivo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field64' => array( 'field' => 'usr_edl',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field65' => array( 'field' => 'usr_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field66' => array( 'field' => 'usr_emergencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field67' => array( 'field' => 'usr_entidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field68' => array( 'field' => 'usr_extension',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field69' => array( 'field' => 'usr_firma',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field70' => array( 'field' => 'usr_firma_b',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field71' => array( 'field' => 'usr_hojaruta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field72' => array( 'field' => 'usr_image',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field73' => array( 'field' => 'usr_inicial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field74' => array( 'field' => 'usr_jefe',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field75' => array( 'field' => 'usr_lname',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field76' => array( 'field' => 'usr_minequipo_grupo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field77' => array( 'field' => 'usr_minequipo_lider',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field78' => array( 'field' => 'usr_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field79' => array( 'field' => 'usr_nombresfull',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field80' => array( 'field' => 'usr_not',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field81' => array( 'field' => 'usr_not_msj',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field82' => array( 'field' => 'usr_personalid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field83' => array( 'field' => 'usr_piso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field84' => array( 'field' => 'usr_rdnkey',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field85' => array( 'field' => 'usr_regpago',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field86' => array( 'field' => 'usr_sessini',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field87' => array( 'field' => 'usr_status',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field88' => array( 'field' => 'usr_status_nomina',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field89' => array( 'field' => 'usr_status_sol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field90' => array( 'field' => 'usr_type_vinc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field91' => array( 'field' => 'usr_type_vinculacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field92' => array( 'field' => 'usr_update_almacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field93' => array( 'field' => 'vacuna_a_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field94' => array( 'field' => 'vacuna_autoriza',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field95' => array( 'field' => 'vacuna_autoriza_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field96' => array( 'field' => 'vacuna_b_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field97' => array( 'field' => 'vacuna_b_fechaprog',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field98' => array( 'field' => 'vacuna_c_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field99' => array( 'field' => 'vacuna_consentimiento_sn',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field100' => array( 'field' => 'vacuna_dosis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field101' => array( 'field' => 'vacuna_etapa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field102' => array( 'field' => 'vacuna_interes',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field103' => array( 'field' => 'vacuna_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field104' => array( 'field' => 'vacuna_obs',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field105' => array( 'field' => 'vacuna_sn',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>