<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'active',
'covid_fecha',
'covid_sn',
'ctrl',
'ctrl_contacto',
'ctrl_pedidoalmacen',
'estado_vinculacion_mincit',
'ext_security_id',
'global_rol',
'global_rol_almacen',
'global_rol_cej',
'global_rol_ci',
'global_rol_ciudadano',
'global_rol_ciudadano_dep',
'global_rol_comacc',
'global_rol_cont',
'global_rol_contratos',
'global_rol_cpanel',
'global_rol_dashboard',
'global_rol_gestion',
'global_rol_gh',
'global_rol_hojar',
'global_rol_inmuebles',
'global_rol_jc3',
'global_rol_me',
'global_rol_procjur',
'global_rol_sid',
'global_rol_siis',
'global_rol_sipi',
'global_rol_th',
'global_rol_zf',
'globla_rol_ct',
'groupid',
'habilita_almacen',
'id_fk',
'idusrglobal',
'Password',
'phone',
'phone1',
'reset_date',
'reset_token',
'sys_anio',
'sys_date',
'sys_disabledate_usr',
'sys_expiration_usr',
'sys_ntries_usr',
'sys_registrationdate_usr',
'sys_time',
'sys_upd_fecha',
'sys_upd_time',
'sys_upd_user',
'sys_update_family_info',
'sys_update_info',
'sys_user',
'upd_date',
'user_dep',
'Username',
'usr_cargo',
'usr_datebirth',
'usr_dep',
'usr_dep_sup',
'usr_dependencia',
'usr_directivo',
'usr_edl',
'usr_email',
'usr_emergencia',
'usr_entidad',
'usr_extension',
'usr_firma',
'usr_firma_b',
'usr_hojaruta',
'usr_image',
'usr_inicial',
'usr_jefe',
'usr_lname',
'usr_minequipo_grupo',
'usr_minequipo_lider',
'usr_name',
'usr_nombresfull',
'usr_not',
'usr_not_msj',
'usr_personalid',
'usr_piso',
'usr_rdnkey',
'usr_regpago',
'usr_sessini',
'usr_status',
'usr_status_nomina',
'usr_status_sol',
'usr_type_vinc',
'usr_type_vinculacion',
'usr_update_almacen',
'vacuna_a_fecha',
'vacuna_autoriza',
'vacuna_autoriza_email',
'vacuna_b_fecha',
'vacuna_b_fechaprog',
'vacuna_c_fecha',
'vacuna_consentimiento_sn',
'vacuna_dosis',
'vacuna_etapa',
'vacuna_interes',
'vacuna_nombre',
'vacuna_obs',
'vacuna_sn' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'active' => array( 'import_field' ),
'covid_fecha' => array( 'import_field1' ),
'covid_sn' => array( 'import_field2' ),
'ctrl' => array( 'import_field3' ),
'ctrl_contacto' => array( 'import_field4' ),
'ctrl_pedidoalmacen' => array( 'import_field5' ),
'estado_vinculacion_mincit' => array( 'import_field6' ),
'ext_security_id' => array( 'import_field7' ),
'global_rol' => array( 'import_field8' ),
'global_rol_almacen' => array( 'import_field9' ),
'global_rol_cej' => array( 'import_field10' ),
'global_rol_ci' => array( 'import_field11' ),
'global_rol_ciudadano' => array( 'import_field12' ),
'global_rol_ciudadano_dep' => array( 'import_field13' ),
'global_rol_comacc' => array( 'import_field14' ),
'global_rol_cont' => array( 'import_field15' ),
'global_rol_contratos' => array( 'import_field16' ),
'global_rol_cpanel' => array( 'import_field17' ),
'global_rol_dashboard' => array( 'import_field18' ),
'global_rol_gestion' => array( 'import_field19' ),
'global_rol_gh' => array( 'import_field20' ),
'global_rol_hojar' => array( 'import_field21' ),
'global_rol_inmuebles' => array( 'import_field22' ),
'global_rol_jc3' => array( 'import_field23' ),
'global_rol_me' => array( 'import_field24' ),
'global_rol_procjur' => array( 'import_field25' ),
'global_rol_sid' => array( 'import_field26' ),
'global_rol_siis' => array( 'import_field27' ),
'global_rol_sipi' => array( 'import_field28' ),
'global_rol_th' => array( 'import_field29' ),
'global_rol_zf' => array( 'import_field30' ),
'globla_rol_ct' => array( 'import_field31' ),
'groupid' => array( 'import_field32' ),
'habilita_almacen' => array( 'import_field33' ),
'id_fk' => array( 'import_field34' ),
'idusrglobal' => array( 'import_field35' ),
'Password' => array( 'import_field36' ),
'phone' => array( 'import_field37' ),
'phone1' => array( 'import_field38' ),
'reset_date' => array( 'import_field39' ),
'reset_token' => array( 'import_field40' ),
'sys_anio' => array( 'import_field41' ),
'sys_date' => array( 'import_field42' ),
'sys_disabledate_usr' => array( 'import_field43' ),
'sys_expiration_usr' => array( 'import_field44' ),
'sys_ntries_usr' => array( 'import_field45' ),
'sys_registrationdate_usr' => array( 'import_field46' ),
'sys_time' => array( 'import_field47' ),
'sys_upd_fecha' => array( 'import_field48' ),
'sys_upd_time' => array( 'import_field49' ),
'sys_upd_user' => array( 'import_field50' ),
'sys_update_family_info' => array( 'import_field51' ),
'sys_update_info' => array( 'import_field52' ),
'sys_user' => array( 'import_field53' ),
'upd_date' => array( 'import_field54' ),
'user_dep' => array( 'import_field55' ),
'Username' => array( 'import_field56' ),
'usr_cargo' => array( 'import_field57' ),
'usr_datebirth' => array( 'import_field58' ),
'usr_dep' => array( 'import_field59' ),
'usr_dep_sup' => array( 'import_field60' ),
'usr_dependencia' => array( 'import_field61' ),
'usr_directivo' => array( 'import_field62' ),
'usr_edl' => array( 'import_field63' ),
'usr_email' => array( 'import_field64' ),
'usr_emergencia' => array( 'import_field65' ),
'usr_entidad' => array( 'import_field66' ),
'usr_extension' => array( 'import_field67' ),
'usr_firma' => array( 'import_field68' ),
'usr_firma_b' => array( 'import_field69' ),
'usr_hojaruta' => array( 'import_field70' ),
'usr_image' => array( 'import_field71' ),
'usr_inicial' => array( 'import_field72' ),
'usr_jefe' => array( 'import_field73' ),
'usr_lname' => array( 'import_field74' ),
'usr_minequipo_grupo' => array( 'import_field75' ),
'usr_minequipo_lider' => array( 'import_field76' ),
'usr_name' => array( 'import_field77' ),
'usr_nombresfull' => array( 'import_field78' ),
'usr_not' => array( 'import_field79' ),
'usr_not_msj' => array( 'import_field80' ),
'usr_personalid' => array( 'import_field81' ),
'usr_piso' => array( 'import_field82' ),
'usr_rdnkey' => array( 'import_field83' ),
'usr_regpago' => array( 'import_field84' ),
'usr_sessini' => array( 'import_field85' ),
'usr_status' => array( 'import_field86' ),
'usr_status_nomina' => array( 'import_field87' ),
'usr_status_sol' => array( 'import_field88' ),
'usr_type_vinc' => array( 'import_field89' ),
'usr_type_vinculacion' => array( 'import_field90' ),
'usr_update_almacen' => array( 'import_field91' ),
'vacuna_a_fecha' => array( 'import_field92' ),
'vacuna_autoriza' => array( 'import_field93' ),
'vacuna_autoriza_email' => array( 'import_field94' ),
'vacuna_b_fecha' => array( 'import_field95' ),
'vacuna_b_fechaprog' => array( 'import_field96' ),
'vacuna_c_fecha' => array( 'import_field97' ),
'vacuna_consentimiento_sn' => array( 'import_field98' ),
'vacuna_dosis' => array( 'import_field99' ),
'vacuna_etapa' => array( 'import_field100' ),
'vacuna_interes' => array( 'import_field101' ),
'vacuna_nombre' => array( 'import_field102' ),
'vacuna_obs' => array( 'import_field103' ),
'vacuna_sn' => array( 'import_field104' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76',
'import_field77',
'import_field78',
'import_field79',
'import_field80',
'import_field81',
'import_field82',
'import_field83',
'import_field84',
'import_field85',
'import_field86',
'import_field87',
'import_field88',
'import_field89',
'import_field90',
'import_field91',
'import_field92',
'import_field93',
'import_field94',
'import_field95',
'import_field96',
'import_field97',
'import_field98',
'import_field99',
'import_field100',
'import_field101',
'import_field102',
'import_field103',
'import_field104' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid',
'import_field55' => 'grid',
'import_field56' => 'grid',
'import_field57' => 'grid',
'import_field58' => 'grid',
'import_field59' => 'grid',
'import_field60' => 'grid',
'import_field61' => 'grid',
'import_field62' => 'grid',
'import_field63' => 'grid',
'import_field64' => 'grid',
'import_field65' => 'grid',
'import_field66' => 'grid',
'import_field67' => 'grid',
'import_field68' => 'grid',
'import_field69' => 'grid',
'import_field70' => 'grid',
'import_field71' => 'grid',
'import_field72' => 'grid',
'import_field73' => 'grid',
'import_field74' => 'grid',
'import_field75' => 'grid',
'import_field76' => 'grid',
'import_field77' => 'grid',
'import_field78' => 'grid',
'import_field79' => 'grid',
'import_field80' => 'grid',
'import_field81' => 'grid',
'import_field82' => 'grid',
'import_field83' => 'grid',
'import_field84' => 'grid',
'import_field85' => 'grid',
'import_field86' => 'grid',
'import_field87' => 'grid',
'import_field88' => 'grid',
'import_field89' => 'grid',
'import_field90' => 'grid',
'import_field91' => 'grid',
'import_field92' => 'grid',
'import_field93' => 'grid',
'import_field94' => 'grid',
'import_field95' => 'grid',
'import_field96' => 'grid',
'import_field97' => 'grid',
'import_field98' => 'grid',
'import_field99' => 'grid',
'import_field100' => 'grid',
'import_field101' => 'grid',
'import_field102' => 'grid',
'import_field103' => 'grid',
'import_field104' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76',
'import_field77',
'import_field78',
'import_field79',
'import_field80',
'import_field81',
'import_field82',
'import_field83',
'import_field84',
'import_field85',
'import_field86',
'import_field87',
'import_field88',
'import_field89',
'import_field90',
'import_field91',
'import_field92',
'import_field93',
'import_field94',
'import_field95',
'import_field96',
'import_field97',
'import_field98',
'import_field99',
'import_field100',
'import_field101',
'import_field102',
'import_field103',
'import_field104' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76',
'import_field77',
'import_field78',
'import_field79',
'import_field80',
'import_field81',
'import_field82',
'import_field83',
'import_field84',
'import_field85',
'import_field86',
'import_field87',
'import_field88',
'import_field89',
'import_field90',
'import_field91',
'import_field92',
'import_field93',
'import_field94',
'import_field95',
'import_field96',
'import_field97',
'import_field98',
'import_field99',
'import_field100',
'import_field101',
'import_field102',
'import_field103',
'import_field104' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'active',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'covid_fecha',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'covid_sn',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'ctrl',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'ctrl_contacto',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'ctrl_pedidoalmacen',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'estado_vinculacion_mincit',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'ext_security_id',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'global_rol',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'global_rol_almacen',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'global_rol_cej',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'global_rol_ci',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'global_rol_ciudadano',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'global_rol_ciudadano_dep',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'global_rol_comacc',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'global_rol_cont',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'global_rol_contratos',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'global_rol_cpanel',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'global_rol_dashboard',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'global_rol_gestion',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'global_rol_gh',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'global_rol_hojar',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'global_rol_inmuebles',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'global_rol_jc3',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'global_rol_me',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'global_rol_procjur',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'global_rol_sid',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'global_rol_siis',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'global_rol_sipi',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'global_rol_th',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'global_rol_zf',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'globla_rol_ct',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'groupid',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'habilita_almacen',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'id_fk',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'idusrglobal',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'Password',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'phone',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'phone1',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'reset_date',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'reset_token',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'sys_anio',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'sys_date',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'sys_disabledate_usr',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'sys_expiration_usr',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'sys_ntries_usr',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'sys_registrationdate_usr',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'sys_time',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'sys_upd_fecha',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'sys_upd_time',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'sys_upd_user',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'sys_update_family_info',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'sys_update_info',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'upd_date',
'type' => 'import_field' ),
'import_field55' => array( 'field' => 'user_dep',
'type' => 'import_field' ),
'import_field56' => array( 'field' => 'Username',
'type' => 'import_field' ),
'import_field57' => array( 'field' => 'usr_cargo',
'type' => 'import_field' ),
'import_field58' => array( 'field' => 'usr_datebirth',
'type' => 'import_field' ),
'import_field59' => array( 'field' => 'usr_dep',
'type' => 'import_field' ),
'import_field60' => array( 'field' => 'usr_dep_sup',
'type' => 'import_field' ),
'import_field61' => array( 'field' => 'usr_dependencia',
'type' => 'import_field' ),
'import_field62' => array( 'field' => 'usr_directivo',
'type' => 'import_field' ),
'import_field63' => array( 'field' => 'usr_edl',
'type' => 'import_field' ),
'import_field64' => array( 'field' => 'usr_email',
'type' => 'import_field' ),
'import_field65' => array( 'field' => 'usr_emergencia',
'type' => 'import_field' ),
'import_field66' => array( 'field' => 'usr_entidad',
'type' => 'import_field' ),
'import_field67' => array( 'field' => 'usr_extension',
'type' => 'import_field' ),
'import_field68' => array( 'field' => 'usr_firma',
'type' => 'import_field' ),
'import_field69' => array( 'field' => 'usr_firma_b',
'type' => 'import_field' ),
'import_field70' => array( 'field' => 'usr_hojaruta',
'type' => 'import_field' ),
'import_field71' => array( 'field' => 'usr_image',
'type' => 'import_field' ),
'import_field72' => array( 'field' => 'usr_inicial',
'type' => 'import_field' ),
'import_field73' => array( 'field' => 'usr_jefe',
'type' => 'import_field' ),
'import_field74' => array( 'field' => 'usr_lname',
'type' => 'import_field' ),
'import_field75' => array( 'field' => 'usr_minequipo_grupo',
'type' => 'import_field' ),
'import_field76' => array( 'field' => 'usr_minequipo_lider',
'type' => 'import_field' ),
'import_field77' => array( 'field' => 'usr_name',
'type' => 'import_field' ),
'import_field78' => array( 'field' => 'usr_nombresfull',
'type' => 'import_field' ),
'import_field79' => array( 'field' => 'usr_not',
'type' => 'import_field' ),
'import_field80' => array( 'field' => 'usr_not_msj',
'type' => 'import_field' ),
'import_field81' => array( 'field' => 'usr_personalid',
'type' => 'import_field' ),
'import_field82' => array( 'field' => 'usr_piso',
'type' => 'import_field' ),
'import_field83' => array( 'field' => 'usr_rdnkey',
'type' => 'import_field' ),
'import_field84' => array( 'field' => 'usr_regpago',
'type' => 'import_field' ),
'import_field85' => array( 'field' => 'usr_sessini',
'type' => 'import_field' ),
'import_field86' => array( 'field' => 'usr_status',
'type' => 'import_field' ),
'import_field87' => array( 'field' => 'usr_status_nomina',
'type' => 'import_field' ),
'import_field88' => array( 'field' => 'usr_status_sol',
'type' => 'import_field' ),
'import_field89' => array( 'field' => 'usr_type_vinc',
'type' => 'import_field' ),
'import_field90' => array( 'field' => 'usr_type_vinculacion',
'type' => 'import_field' ),
'import_field91' => array( 'field' => 'usr_update_almacen',
'type' => 'import_field' ),
'import_field92' => array( 'field' => 'vacuna_a_fecha',
'type' => 'import_field' ),
'import_field93' => array( 'field' => 'vacuna_autoriza',
'type' => 'import_field' ),
'import_field94' => array( 'field' => 'vacuna_autoriza_email',
'type' => 'import_field' ),
'import_field95' => array( 'field' => 'vacuna_b_fecha',
'type' => 'import_field' ),
'import_field96' => array( 'field' => 'vacuna_b_fechaprog',
'type' => 'import_field' ),
'import_field97' => array( 'field' => 'vacuna_c_fecha',
'type' => 'import_field' ),
'import_field98' => array( 'field' => 'vacuna_consentimiento_sn',
'type' => 'import_field' ),
'import_field99' => array( 'field' => 'vacuna_dosis',
'type' => 'import_field' ),
'import_field100' => array( 'field' => 'vacuna_etapa',
'type' => 'import_field' ),
'import_field101' => array( 'field' => 'vacuna_interes',
'type' => 'import_field' ),
'import_field102' => array( 'field' => 'vacuna_nombre',
'type' => 'import_field' ),
'import_field103' => array( 'field' => 'vacuna_obs',
'type' => 'import_field' ),
'import_field104' => array( 'field' => 'vacuna_sn',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>