<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'CDP' => array( 'totalsType' => '' ),
'CID' => array( 'totalsType' => '' ),
'Compromisos' => array( 'totalsType' => '' ),
'Cuentas por Pagar' => array( 'totalsType' => '' ),
'Dependencia' => array( 'totalsType' => '' ),
'Dependencia Descripcion' => array( 'totalsType' => '' ),
'Descripcion' => array( 'totalsType' => '' ),
'Entidad Descripcion' => array( 'totalsType' => '' ),
'Entidad Nit' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'Estado Cuenta' => array( 'totalsType' => '' ),
'Fecha de Creacion' => array( 'totalsType' => '' ),
'Fecha de Registro' => array( 'totalsType' => '' ),
'Fecha Documento Soporte' => array( 'totalsType' => '' ),
'Fuente' => array( 'totalsType' => '' ),
'Identificacion' => array( 'totalsType' => '' ),
'Medio de Pago' => array( 'totalsType' => '' ),
'Nombre Razon Social' => array( 'totalsType' => '' ),
'Numero Cuenta' => array( 'totalsType' => '' ),
'Numero Documento' => array( 'totalsType' => '' ),
'Numero Documento Soporte' => array( 'totalsType' => '' ),
'Obligaciones' => array( 'totalsType' => '' ),
'Observaciones' => array( 'totalsType' => '' ),
'Ordenes de Pago' => array( 'totalsType' => '' ),
'Recurso' => array( 'totalsType' => '' ),
'Reintegros' => array( 'totalsType' => '' ),
'Rubro' => array( 'totalsType' => '' ),
'Saldo por Utilizar' => array( 'totalsType' => '' ),
'Situacion' => array( 'totalsType' => '' ),
'Solicitud CDP' => array( 'totalsType' => '' ),
'Tipo Cuenta' => array( 'totalsType' => '' ),
'Tipo Documento Soporte' => array( 'totalsType' => '' ),
'Tipo Identificacion' => array( 'totalsType' => '' ),
'Valor Actual' => array( 'totalsType' => '' ),
'Valor Inicial' => array( 'totalsType' => '' ),
'Valor Operaciones' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Numero Documento',
'Fecha de Registro',
'Fecha de Creacion',
'Estado',
'Dependencia',
'Dependencia Descripcion',
'Rubro',
'Descripcion',
'Fuente',
'Recurso',
'Situacion',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Saldo por Utilizar',
'Tipo Identificacion',
'Identificacion',
'Nombre Razon Social',
'Medio de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Reintegros',
'Fecha Documento Soporte',
'Tipo Documento Soporte',
'Numero Documento Soporte',
'Observaciones' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Numero Documento' => array( 'simple_grid_field1',
'simple_grid_field' ),
'Fecha de Registro' => array( 'simple_grid_field2',
'simple_grid_field36' ),
'Fecha de Creacion' => array( 'simple_grid_field3',
'simple_grid_field37' ),
'Estado' => array( 'simple_grid_field4',
'simple_grid_field38' ),
'Dependencia' => array( 'simple_grid_field5',
'simple_grid_field39' ),
'Dependencia Descripcion' => array( 'simple_grid_field6',
'simple_grid_field40' ),
'Rubro' => array( 'simple_grid_field7',
'simple_grid_field41' ),
'Descripcion' => array( 'simple_grid_field8',
'simple_grid_field42' ),
'Fuente' => array( 'simple_grid_field9',
'simple_grid_field43' ),
'Recurso' => array( 'simple_grid_field10',
'simple_grid_field44' ),
'Situacion' => array( 'simple_grid_field11',
'simple_grid_field45' ),
'Valor Inicial' => array( 'simple_grid_field12',
'simple_grid_field46' ),
'Valor Operaciones' => array( 'simple_grid_field13',
'simple_grid_field47' ),
'Valor Actual' => array( 'simple_grid_field14',
'simple_grid_field48' ),
'Saldo por Utilizar' => array( 'simple_grid_field15',
'simple_grid_field49' ),
'Tipo Identificacion' => array( 'simple_grid_field16',
'simple_grid_field50' ),
'Identificacion' => array( 'simple_grid_field17',
'simple_grid_field51' ),
'Nombre Razon Social' => array( 'simple_grid_field18',
'simple_grid_field52' ),
'Medio de Pago' => array( 'simple_grid_field19',
'simple_grid_field53' ),
'Tipo Cuenta' => array( 'simple_grid_field20',
'simple_grid_field54' ),
'Numero Cuenta' => array( 'simple_grid_field21',
'simple_grid_field55' ),
'Estado Cuenta' => array( 'simple_grid_field22',
'simple_grid_field56' ),
'Entidad Nit' => array( 'simple_grid_field23',
'simple_grid_field57' ),
'Entidad Descripcion' => array( 'simple_grid_field24',
'simple_grid_field58' ),
'Solicitud CDP' => array( 'simple_grid_field25',
'simple_grid_field59' ),
'CDP' => array( 'simple_grid_field26',
'simple_grid_field60' ),
'Compromisos' => array( 'simple_grid_field27',
'simple_grid_field61' ),
'Cuentas por Pagar' => array( 'simple_grid_field28',
'simple_grid_field62' ),
'Obligaciones' => array( 'simple_grid_field29',
'simple_grid_field63' ),
'Ordenes de Pago' => array( 'simple_grid_field30',
'simple_grid_field64' ),
'Reintegros' => array( 'simple_grid_field31',
'simple_grid_field65' ),
'Fecha Documento Soporte' => array( 'simple_grid_field32',
'simple_grid_field66' ),
'Tipo Documento Soporte' => array( 'simple_grid_field33',
'simple_grid_field67' ),
'Numero Documento Soporte' => array( 'simple_grid_field34',
'simple_grid_field68' ),
'Observaciones' => array( 'simple_grid_field35',
'simple_grid_field69' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field36',
'simple_grid_field2',
'simple_grid_field37',
'simple_grid_field3',
'simple_grid_field38',
'simple_grid_field4',
'simple_grid_field39',
'simple_grid_field5',
'simple_grid_field40',
'simple_grid_field6',
'simple_grid_field41',
'simple_grid_field7',
'simple_grid_field42',
'simple_grid_field8',
'simple_grid_field43',
'simple_grid_field9',
'simple_grid_field44',
'simple_grid_field10',
'simple_grid_field45',
'simple_grid_field11',
'simple_grid_field46',
'simple_grid_field12',
'simple_grid_field47',
'simple_grid_field13',
'simple_grid_field48',
'simple_grid_field14',
'simple_grid_field49',
'simple_grid_field15',
'simple_grid_field50',
'simple_grid_field16',
'simple_grid_field51',
'simple_grid_field17',
'simple_grid_field52',
'simple_grid_field18',
'simple_grid_field53',
'simple_grid_field19',
'simple_grid_field54',
'simple_grid_field20',
'simple_grid_field55',
'simple_grid_field21',
'simple_grid_field56',
'simple_grid_field22',
'simple_grid_field57',
'simple_grid_field23',
'simple_grid_field58',
'simple_grid_field24',
'simple_grid_field59',
'simple_grid_field25',
'simple_grid_field60',
'simple_grid_field26',
'simple_grid_field61',
'simple_grid_field27',
'simple_grid_field62',
'simple_grid_field28',
'simple_grid_field63',
'simple_grid_field29',
'simple_grid_field64',
'simple_grid_field30',
'simple_grid_field65',
'simple_grid_field31',
'simple_grid_field66',
'simple_grid_field32',
'simple_grid_field67',
'simple_grid_field33',
'simple_grid_field68',
'simple_grid_field34',
'simple_grid_field69',
'simple_grid_field35' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field35' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'Numero_Documento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Fecha_de_Registro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Fecha_de_Creacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Dependencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Dependencia_Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Rubro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Fuente_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Recurso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'Situacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Inicial_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Operaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_Actual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'Saldo_por_Utilizar_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Identificacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'Identificacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'Nombre_Razon_Social_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'Medio_de_Pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'Numero_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'Estado_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'Entidad_Nit_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'Entidad_Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'Solicitud_CDP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'CDP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'Compromisos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'Cuentas_por_Pagar_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'Obligaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'Ordenes_de_Pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'Reintegros_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'Fecha_Documento_Soporte_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_Documento_Soporte_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'Numero_Documento_Soporte_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'Observaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'Numero_Documento_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_de_Registro_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_de_Creacion_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Estado_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Dependencia_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Dependencia_Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Rubro_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Fuente_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Recurso_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'Situacion_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Inicial_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Operaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Actual_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'Saldo_por_Utilizar_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Identificacion_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'Identificacion_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'Nombre_Razon_Social_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'Medio_de_Pago_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'Numero_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'Estado_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'Entidad_Nit_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'Entidad_Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'Solicitud_CDP_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'CDP_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'Compromisos_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'Cuentas_por_Pagar_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'Obligaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'Ordenes_de_Pago_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'Reintegros_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_Documento_Soporte_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_Documento_Soporte_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'Numero_Documento_Soporte_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'Observaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 35,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Numero Documento',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Numero Documento',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'Fecha de Registro',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Fecha de Registro',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'Fecha de Creacion',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Fecha de Creacion',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'Estado',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'Estado',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'Dependencia',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'Dependencia',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'Dependencia Descripcion',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'Dependencia Descripcion',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'Rubro',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'Rubro',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'Descripcion',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'Descripcion',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'Fuente',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'Fuente',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'Recurso',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'Recurso',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'Situacion',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'Situacion',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'Valor Inicial',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'Valor Inicial',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'Valor Operaciones',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'Valor Operaciones',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'Valor Actual',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'Valor Actual',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'Saldo por Utilizar',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'Saldo por Utilizar',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'Tipo Identificacion',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'Tipo Identificacion',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'Identificacion',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'Identificacion',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'Nombre Razon Social',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'Nombre Razon Social',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'Medio de Pago',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'Medio de Pago',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'Tipo Cuenta',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'Tipo Cuenta',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'Numero Cuenta',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'Numero Cuenta',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'Estado Cuenta',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'Estado Cuenta',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'Entidad Nit',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'Entidad Nit',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'Entidad Descripcion',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'Entidad Descripcion',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'Solicitud CDP',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'Solicitud CDP',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'CDP',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'CDP',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'Compromisos',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'Compromisos',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'Cuentas por Pagar',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'Cuentas por Pagar',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'Obligaciones',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'Obligaciones',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'Ordenes de Pago',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'Ordenes de Pago',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'Reintegros',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'Reintegros',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'Fecha Documento Soporte',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'Fecha Documento Soporte',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'Tipo Documento Soporte',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'Tipo Documento Soporte',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'Numero Documento Soporte',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'Numero Documento Soporte',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'Observaciones',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'Observaciones',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field1' => array( 'field' => 'Numero Documento',
'type' => 'grid_field' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'Numero Documento' ),
'simple_grid_field2' => array( 'field' => 'Fecha de Registro',
'type' => 'grid_field' ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'Fecha de Registro' ),
'simple_grid_field3' => array( 'field' => 'Fecha de Creacion',
'type' => 'grid_field' ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'Fecha de Creacion' ),
'simple_grid_field4' => array( 'field' => 'Estado',
'type' => 'grid_field' ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'Estado' ),
'simple_grid_field5' => array( 'field' => 'Dependencia',
'type' => 'grid_field' ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'Dependencia' ),
'simple_grid_field6' => array( 'field' => 'Dependencia Descripcion',
'type' => 'grid_field' ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'Dependencia Descripcion' ),
'simple_grid_field7' => array( 'field' => 'Rubro',
'type' => 'grid_field' ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'Rubro' ),
'simple_grid_field8' => array( 'field' => 'Descripcion',
'type' => 'grid_field' ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'Descripcion' ),
'simple_grid_field9' => array( 'field' => 'Fuente',
'type' => 'grid_field' ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'Fuente' ),
'simple_grid_field10' => array( 'field' => 'Recurso',
'type' => 'grid_field' ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'Recurso' ),
'simple_grid_field11' => array( 'field' => 'Situacion',
'type' => 'grid_field' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'Situacion' ),
'simple_grid_field12' => array( 'field' => 'Valor Inicial',
'type' => 'grid_field' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'Valor Inicial' ),
'simple_grid_field13' => array( 'field' => 'Valor Operaciones',
'type' => 'grid_field' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'Valor Operaciones' ),
'simple_grid_field14' => array( 'field' => 'Valor Actual',
'type' => 'grid_field' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'Valor Actual' ),
'simple_grid_field15' => array( 'field' => 'Saldo por Utilizar',
'type' => 'grid_field' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'Saldo por Utilizar' ),
'simple_grid_field16' => array( 'field' => 'Tipo Identificacion',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Identificacion' ),
'simple_grid_field17' => array( 'field' => 'Identificacion',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'Identificacion' ),
'simple_grid_field18' => array( 'field' => 'Nombre Razon Social',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'Nombre Razon Social' ),
'simple_grid_field19' => array( 'field' => 'Medio de Pago',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'Medio de Pago' ),
'simple_grid_field20' => array( 'field' => 'Tipo Cuenta',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Cuenta' ),
'simple_grid_field21' => array( 'field' => 'Numero Cuenta',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'Numero Cuenta' ),
'simple_grid_field22' => array( 'field' => 'Estado Cuenta',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'Estado Cuenta' ),
'simple_grid_field23' => array( 'field' => 'Entidad Nit',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'Entidad Nit' ),
'simple_grid_field24' => array( 'field' => 'Entidad Descripcion',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'Entidad Descripcion' ),
'simple_grid_field25' => array( 'field' => 'Solicitud CDP',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'Solicitud CDP' ),
'simple_grid_field26' => array( 'field' => 'CDP',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'CDP' ),
'simple_grid_field27' => array( 'field' => 'Compromisos',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'Compromisos' ),
'simple_grid_field28' => array( 'field' => 'Cuentas por Pagar',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'Cuentas por Pagar' ),
'simple_grid_field29' => array( 'field' => 'Obligaciones',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'Obligaciones' ),
'simple_grid_field30' => array( 'field' => 'Ordenes de Pago',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'Ordenes de Pago' ),
'simple_grid_field31' => array( 'field' => 'Reintegros',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'Reintegros' ),
'simple_grid_field32' => array( 'field' => 'Fecha Documento Soporte',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'Fecha Documento Soporte' ),
'simple_grid_field33' => array( 'field' => 'Tipo Documento Soporte',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Documento Soporte' ),
'simple_grid_field34' => array( 'field' => 'Numero Documento Soporte',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'Numero Documento Soporte' ),
'simple_grid_field35' => array( 'field' => 'Observaciones',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'Observaciones' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>