<?php
			$optionsArray = array( 'totals' => array( 'CDP' => array( 'totalsType' => '' ),
'CID' => array( 'totalsType' => '' ),
'Compromisos' => array( 'totalsType' => '' ),
'Cuentas por Pagar' => array( 'totalsType' => '' ),
'Dependencia' => array( 'totalsType' => '' ),
'Dependencia Descripcion' => array( 'totalsType' => '' ),
'Descripcion' => array( 'totalsType' => '' ),
'Entidad Descripcion' => array( 'totalsType' => '' ),
'Entidad Nit' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'Estado Cuenta' => array( 'totalsType' => '' ),
'Fecha de Creacion' => array( 'totalsType' => '' ),
'Fecha de Registro' => array( 'totalsType' => '' ),
'Fecha Documento Soporte' => array( 'totalsType' => '' ),
'Fuente' => array( 'totalsType' => '' ),
'Identificacion' => array( 'totalsType' => '' ),
'Medio de Pago' => array( 'totalsType' => '' ),
'Nombre Razon Social' => array( 'totalsType' => '' ),
'Numero Cuenta' => array( 'totalsType' => '' ),
'Numero Documento' => array( 'totalsType' => '' ),
'Numero Documento Soporte' => array( 'totalsType' => '' ),
'Obligaciones' => array( 'totalsType' => '' ),
'Observaciones' => array( 'totalsType' => '' ),
'Ordenes de Pago' => array( 'totalsType' => '' ),
'Recurso' => array( 'totalsType' => '' ),
'Reintegros' => array( 'totalsType' => '' ),
'Rubro' => array( 'totalsType' => '' ),
'Saldo por Utilizar' => array( 'totalsType' => '' ),
'Situacion' => array( 'totalsType' => '' ),
'Solicitud CDP' => array( 'totalsType' => '' ),
'Tipo Cuenta' => array( 'totalsType' => '' ),
'Tipo Documento Soporte' => array( 'totalsType' => '' ),
'Tipo Identificacion' => array( 'totalsType' => '' ),
'Valor Actual' => array( 'totalsType' => '' ),
'Valor Inicial' => array( 'totalsType' => '' ),
'Valor Operaciones' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Numero Documento',
'Fecha de Registro',
'Fecha de Creacion',
'Estado',
'Dependencia',
'Dependencia Descripcion',
'Rubro',
'Descripcion',
'Fuente',
'Recurso',
'Situacion',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Saldo por Utilizar',
'Tipo Identificacion',
'Identificacion',
'Nombre Razon Social',
'Medio de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Reintegros',
'Fecha Documento Soporte',
'Tipo Documento Soporte',
'Numero Documento Soporte',
'Observaciones' ),
'exportFields' => array( 'Numero Documento',
'Fecha de Registro',
'Fecha de Creacion',
'Estado',
'Dependencia',
'Dependencia Descripcion',
'Rubro',
'Descripcion',
'Fuente',
'Recurso',
'Situacion',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Saldo por Utilizar',
'Tipo Identificacion',
'Identificacion',
'Nombre Razon Social',
'Medio de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Reintegros',
'Fecha Documento Soporte',
'Tipo Documento Soporte',
'Numero Documento Soporte',
'Observaciones' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Numero Documento' => array( 'export_field1' ),
'Fecha de Registro' => array( 'export_field2' ),
'Fecha de Creacion' => array( 'export_field3' ),
'Estado' => array( 'export_field4' ),
'Dependencia' => array( 'export_field5' ),
'Dependencia Descripcion' => array( 'export_field6' ),
'Rubro' => array( 'export_field7' ),
'Descripcion' => array( 'export_field8' ),
'Fuente' => array( 'export_field9' ),
'Recurso' => array( 'export_field10' ),
'Situacion' => array( 'export_field11' ),
'Valor Inicial' => array( 'export_field12' ),
'Valor Operaciones' => array( 'export_field13' ),
'Valor Actual' => array( 'export_field14' ),
'Saldo por Utilizar' => array( 'export_field15' ),
'Tipo Identificacion' => array( 'export_field16' ),
'Identificacion' => array( 'export_field17' ),
'Nombre Razon Social' => array( 'export_field18' ),
'Medio de Pago' => array( 'export_field19' ),
'Tipo Cuenta' => array( 'export_field20' ),
'Numero Cuenta' => array( 'export_field21' ),
'Estado Cuenta' => array( 'export_field22' ),
'Entidad Nit' => array( 'export_field23' ),
'Entidad Descripcion' => array( 'export_field24' ),
'Solicitud CDP' => array( 'export_field25' ),
'CDP' => array( 'export_field26' ),
'Compromisos' => array( 'export_field27' ),
'Cuentas por Pagar' => array( 'export_field28' ),
'Obligaciones' => array( 'export_field29' ),
'Ordenes de Pago' => array( 'export_field30' ),
'Reintegros' => array( 'export_field31' ),
'Fecha Documento Soporte' => array( 'export_field32' ),
'Tipo Documento Soporte' => array( 'export_field33' ),
'Numero Documento Soporte' => array( 'export_field34' ),
'Observaciones' => array( 'export_field35' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'Numero Documento',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Fecha de Registro',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Fecha de Creacion',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Estado',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Dependencia',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Dependencia Descripcion',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Rubro',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Descripcion',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Fuente',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Recurso',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Situacion',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Valor Inicial',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Valor Operaciones',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Valor Actual',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Saldo por Utilizar',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Tipo Identificacion',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Identificacion',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Nombre Razon Social',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Medio de Pago',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Tipo Cuenta',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'Numero Cuenta',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'Estado Cuenta',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'Entidad Nit',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'Entidad Descripcion',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Solicitud CDP',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'CDP',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Compromisos',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'Cuentas por Pagar',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'Obligaciones',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'Ordenes de Pago',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'Reintegros',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'Fecha Documento Soporte',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'Tipo Documento Soporte',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'Numero Documento Soporte',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'Observaciones',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>