<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Numero Documento',
'Fecha de Registro',
'Fecha de Creacion',
'Estado',
'Valor Actual',
'Valor Deducciones',
'Valor Oblig no Orden',
'Tipo Identificacion',
'Identificacion',
'Nombre Razon Social',
'Medio de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion',
'Dependencia',
'Dependencia Descripcion',
'Rubro',
'Descripcion',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual1',
'Saldo por Utilizar',
'Fuente',
'Situacion',
'Recurso',
'Concepto',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Fecha Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Reintegros',
'Fecha Doc Soporte Compromiso',
'Tipo Doc Soporte Compromiso',
'Num Doc Soporte Compromiso',
'Objeto del Compromiso' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Numero Documento' => array( 'import_field1' ),
'Fecha de Registro' => array( 'import_field2' ),
'Fecha de Creacion' => array( 'import_field3' ),
'Estado' => array( 'import_field4' ),
'Valor Actual' => array( 'import_field5' ),
'Valor Deducciones' => array( 'import_field6' ),
'Valor Oblig no Orden' => array( 'import_field7' ),
'Tipo Identificacion' => array( 'import_field8' ),
'Identificacion' => array( 'import_field9' ),
'Nombre Razon Social' => array( 'import_field10' ),
'Medio de Pago' => array( 'import_field11' ),
'Tipo Cuenta' => array( 'import_field12' ),
'Numero Cuenta' => array( 'import_field13' ),
'Estado Cuenta' => array( 'import_field14' ),
'Entidad Nit' => array( 'import_field15' ),
'Entidad Descripcion' => array( 'import_field16' ),
'Dependencia' => array( 'import_field17' ),
'Dependencia Descripcion' => array( 'import_field18' ),
'Rubro' => array( 'import_field19' ),
'Descripcion' => array( 'import_field20' ),
'Valor Inicial' => array( 'import_field21' ),
'Valor Operaciones' => array( 'import_field22' ),
'Valor Actual1' => array( 'import_field23' ),
'Saldo por Utilizar' => array( 'import_field24' ),
'Fuente' => array( 'import_field25' ),
'Situacion' => array( 'import_field26' ),
'Recurso' => array( 'import_field27' ),
'Concepto' => array( 'import_field28' ),
'Solicitud CDP' => array( 'import_field29' ),
'CDP' => array( 'import_field30' ),
'Compromisos' => array( 'import_field31' ),
'Cuentas por Pagar' => array( 'import_field32' ),
'Fecha Cuentas por Pagar' => array( 'import_field33' ),
'Obligaciones' => array( 'import_field34' ),
'Ordenes de Pago' => array( 'import_field35' ),
'Reintegros' => array( 'import_field36' ),
'Fecha Doc Soporte Compromiso' => array( 'import_field37' ),
'Tipo Doc Soporte Compromiso' => array( 'import_field38' ),
'Num Doc Soporte Compromiso' => array( 'import_field39' ),
'Objeto del Compromiso' => array( 'import_field40' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'Numero Documento',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Fecha de Registro',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Fecha de Creacion',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Valor Actual',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Valor Deducciones',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Valor Oblig no Orden',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Tipo Identificacion',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Identificacion',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Nombre Razon Social',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Medio de Pago',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Tipo Cuenta',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Numero Cuenta',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Estado Cuenta',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Entidad Nit',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Entidad Descripcion',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Dependencia',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Dependencia Descripcion',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Rubro',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Descripcion',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'Valor Inicial',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'Valor Operaciones',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'Valor Actual1',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'Saldo por Utilizar',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'Fuente',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'Situacion',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Recurso',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Concepto',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'Solicitud CDP',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'CDP',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'Compromisos',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'Cuentas por Pagar',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'Fecha Cuentas por Pagar',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'Obligaciones',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'Ordenes de Pago',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'Reintegros',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'Fecha Doc Soporte Compromiso',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'Tipo Doc Soporte Compromiso',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'Num Doc Soporte Compromiso',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'Objeto del Compromiso',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>