<?php
			$optionsArray = array( 'totals' => array( 'COMPROMISO' => array( 'totalsType' => '' ),
'CTA' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'FUENTE' => array( 'totalsType' => '' ),
'ITEM' => array( 'totalsType' => '' ),
'NOMBRE UEJ' => array( 'totalsType' => '' ),
'OBJ' => array( 'totalsType' => '' ),
'OBLIGACION' => array( 'totalsType' => '' ),
'ORD' => array( 'totalsType' => '' ),
'ORDEN PAGO' => array( 'totalsType' => '' ),
'PAGOS' => array( 'totalsType' => '' ),
'REC' => array( 'totalsType' => '' ),
'RID' => array( 'totalsType' => '' ),
'RUBRO' => array( 'totalsType' => '' ),
'SIT' => array( 'totalsType' => '' ),
'SORORD' => array( 'totalsType' => '' ),
'SUBCTA' => array( 'totalsType' => '' ),
'SUBITEM' => array( 'totalsType' => '' ),
'SUBITEM 2' => array( 'totalsType' => '' ),
'TIPO' => array( 'totalsType' => '' ),
'UEJ' => array( 'totalsType' => '' ),
'VALOR CONSTITUIDO' => array( 'totalsType' => '' ),
'VALOR MAXIMO A CONSTITUIR' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'UEJ',
'NOMBRE UEJ',
'RUBRO',
'TIPO',
'CTA',
'SUBCTA',
'OBJ',
'ORD',
'SORORD',
'ITEM',
'SUBITEM',
'SUBITEM 2',
'FUENTE',
'REC',
'SIT',
'DESCRIPCION',
'VALOR MAXIMO A CONSTITUIR',
'VALOR CONSTITUIDO',
'COMPROMISO',
'OBLIGACION',
'ORDEN PAGO',
'PAGOS' ),
'exportFields' => array( 'UEJ',
'NOMBRE UEJ',
'RUBRO',
'TIPO',
'CTA',
'SUBCTA',
'OBJ',
'ORD',
'SORORD',
'ITEM',
'SUBITEM',
'SUBITEM 2',
'FUENTE',
'REC',
'SIT',
'DESCRIPCION',
'VALOR MAXIMO A CONSTITUIR',
'VALOR CONSTITUIDO',
'COMPROMISO',
'OBLIGACION',
'ORDEN PAGO',
'PAGOS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'UEJ' => array( 'export_field1' ),
'NOMBRE UEJ' => array( 'export_field2' ),
'RUBRO' => array( 'export_field3' ),
'TIPO' => array( 'export_field4' ),
'CTA' => array( 'export_field5' ),
'SUBCTA' => array( 'export_field6' ),
'OBJ' => array( 'export_field7' ),
'ORD' => array( 'export_field8' ),
'SORORD' => array( 'export_field9' ),
'ITEM' => array( 'export_field10' ),
'SUBITEM' => array( 'export_field11' ),
'SUBITEM 2' => array( 'export_field12' ),
'FUENTE' => array( 'export_field13' ),
'REC' => array( 'export_field14' ),
'SIT' => array( 'export_field15' ),
'DESCRIPCION' => array( 'export_field16' ),
'VALOR MAXIMO A CONSTITUIR' => array( 'export_field17' ),
'VALOR CONSTITUIDO' => array( 'export_field18' ),
'COMPROMISO' => array( 'export_field19' ),
'OBLIGACION' => array( 'export_field20' ),
'ORDEN PAGO' => array( 'export_field21' ),
'PAGOS' => array( 'export_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'UEJ',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'NOMBRE UEJ',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'RUBRO',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'TIPO',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'CTA',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'SUBCTA',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'OBJ',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'ORD',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'SORORD',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'ITEM',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'SUBITEM',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'SUBITEM 2',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'FUENTE',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'REC',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'SIT',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'VALOR MAXIMO A CONSTITUIR',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'VALOR CONSTITUIDO',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'COMPROMISO',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'OBLIGACION',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'ORDEN PAGO',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'PAGOS',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>