<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'UEJ',
'NOMBRE UEJ',
'RUBRO',
'TIPO',
'CTA',
'SUBCTA',
'OBJ',
'ORD',
'SORORD',
'ITEM',
'SUBITEM',
'SUBITEM 2',
'FUENTE',
'REC',
'SIT',
'DESCRIPCION',
'VALOR MAXIMO A CONSTITUIR',
'VALOR CONSTITUIDO',
'COMPROMISO',
'OBLIGACION',
'ORDEN PAGO',
'PAGOS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'UEJ' => array( 'import_field1' ),
'NOMBRE UEJ' => array( 'import_field2' ),
'RUBRO' => array( 'import_field3' ),
'TIPO' => array( 'import_field4' ),
'CTA' => array( 'import_field5' ),
'SUBCTA' => array( 'import_field6' ),
'OBJ' => array( 'import_field7' ),
'ORD' => array( 'import_field8' ),
'SORORD' => array( 'import_field9' ),
'ITEM' => array( 'import_field10' ),
'SUBITEM' => array( 'import_field11' ),
'SUBITEM 2' => array( 'import_field12' ),
'FUENTE' => array( 'import_field13' ),
'REC' => array( 'import_field14' ),
'SIT' => array( 'import_field15' ),
'DESCRIPCION' => array( 'import_field16' ),
'VALOR MAXIMO A CONSTITUIR' => array( 'import_field17' ),
'VALOR CONSTITUIDO' => array( 'import_field18' ),
'COMPROMISO' => array( 'import_field19' ),
'OBLIGACION' => array( 'import_field20' ),
'ORDEN PAGO' => array( 'import_field21' ),
'PAGOS' => array( 'import_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'UEJ',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'NOMBRE UEJ',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'RUBRO',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'TIPO',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'CTA',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'SUBCTA',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'OBJ',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'ORD',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'SORORD',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'ITEM',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'SUBITEM',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'SUBITEM 2',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'FUENTE',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'REC',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'SIT',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'DESCRIPCION',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'VALOR MAXIMO A CONSTITUIR',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'VALOR CONSTITUIDO',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'COMPROMISO',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'OBLIGACION',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'ORDEN PAGO',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'PAGOS',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>