<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'VIGENCIA',
'CODIGO_BPIN',
'FICHA_BPIN',
'NOMBRE UEJ',
'RUBRO',
'USO_SN',
'TIPO',
'DESCRIPCION',
'APR. VIGENTE',
'DEPENDENCIA_ID',
'RESPONSABLE_ID',
'DEPENDENCIA_SUP_ID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'VIGENCIA' => array( 'import_field1' ),
'CODIGO_BPIN' => array( 'import_field2' ),
'FICHA_BPIN' => array( 'import_field3' ),
'NOMBRE UEJ' => array( 'import_field7' ),
'RUBRO' => array( 'import_field8' ),
'USO_SN' => array( 'import_field9' ),
'TIPO' => array( 'import_field10' ),
'DESCRIPCION' => array( 'import_field22' ),
'APR. VIGENTE' => array( 'import_field26' ),
'DEPENDENCIA_ID' => array( 'import_field36' ),
'RESPONSABLE_ID' => array( 'import_field37' ),
'DEPENDENCIA_SUP_ID' => array( 'import_field38' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field22',
'import_field26',
'import_field36',
'import_field37',
'import_field38' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field22' => 'grid',
'import_field26' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field22',
'import_field26',
'import_field36',
'import_field37',
'import_field38' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field22',
'import_field26',
'import_field36',
'import_field37',
'import_field38' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'VIGENCIA',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'CODIGO_BPIN',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'FICHA_BPIN',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'NOMBRE UEJ',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'RUBRO',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'USO_SN',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'TIPO',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'DESCRIPCION',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'APR. VIGENTE',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'DEPENDENCIA_ID',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'RESPONSABLE_ID',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'DEPENDENCIA_SUP_ID',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>