<?php
			$optionsArray = array( 'totals' => array( 'id_transac' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'CODIGO_BPIN' => array( 'totalsType' => '' ),
'FICHA_BPIN' => array( 'totalsType' => '' ),
'UEJ_MIN' => array( 'totalsType' => '' ),
'NOMBRE UEJ' => array( 'totalsType' => '' ),
'RUBRO' => array( 'totalsType' => '' ),
'USO_SN' => array( 'totalsType' => '' ),
'TIPO' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'APR. VIGENTE' => array( 'totalsType' => '' ),
'DEPENDENCIA_ID' => array( 'totalsType' => '' ),
'RESPONSABLE_ID' => array( 'totalsType' => '' ),
'DEPENDENCIA_SUP_ID' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'VIGENCIA',
'CODIGO_BPIN',
'FICHA_BPIN',
'NOMBRE UEJ',
'RUBRO',
'USO_SN',
'TIPO',
'DESCRIPCION',
'APR. VIGENTE',
'DEPENDENCIA_ID',
'RESPONSABLE_ID',
'DEPENDENCIA_SUP_ID' ),
'exportFields' => array( 'VIGENCIA',
'CODIGO_BPIN',
'FICHA_BPIN',
'NOMBRE UEJ',
'RUBRO',
'USO_SN',
'TIPO',
'DESCRIPCION',
'APR. VIGENTE',
'DEPENDENCIA_ID',
'RESPONSABLE_ID',
'DEPENDENCIA_SUP_ID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'VIGENCIA' => array( 'export_field1' ),
'CODIGO_BPIN' => array( 'export_field2' ),
'FICHA_BPIN' => array( 'export_field3' ),
'NOMBRE UEJ' => array( 'export_field7' ),
'RUBRO' => array( 'export_field8' ),
'USO_SN' => array( 'export_field9' ),
'TIPO' => array( 'export_field10' ),
'DESCRIPCION' => array( 'export_field22' ),
'APR. VIGENTE' => array( 'export_field26' ),
'DEPENDENCIA_ID' => array( 'export_field36' ),
'RESPONSABLE_ID' => array( 'export_field37' ),
'DEPENDENCIA_SUP_ID' => array( 'export_field38' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field22',
'export_field26',
'export_field36',
'export_field37',
'export_field38' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field22' => 'grid',
'export_field26' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field22',
'export_field26',
'export_field36',
'export_field37',
'export_field38' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field22',
'export_field26',
'export_field36',
'export_field37',
'export_field38' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'VIGENCIA',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'CODIGO_BPIN',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'FICHA_BPIN',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'NOMBRE UEJ',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'RUBRO',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'USO_SN',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'TIPO',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'APR. VIGENTE',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'DEPENDENCIA_ID',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'RESPONSABLE_ID',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'DEPENDENCIA_SUP_ID',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>