<?php
			$optionsArray = array( 'master' => array( 'funcionario' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'Username',
'usr_email',
'usr_name',
'usr_lname',
'usr_personalid',
'global_rol_almacen',
'global_rol_contratos',
'sys_user',
'sys_date',
'sys_time',
'usr_dep',
'usr_cargo',
'usr_extension',
'usr_datebirth',
'active',
'groupid',
'id_fk',
'phone',
'usr_status',
'usr_type_vinc' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Username' => array( 'integrated_edit_field1' ),
'usr_email' => array( 'integrated_edit_field3' ),
'usr_name' => array( 'integrated_edit_field4' ),
'usr_lname' => array( 'integrated_edit_field5' ),
'usr_personalid' => array( 'integrated_edit_field7' ),
'global_rol_almacen' => array( 'integrated_edit_field27' ),
'global_rol_contratos' => array( 'integrated_edit_field29' ),
'sys_user' => array( 'integrated_edit_field49' ),
'sys_date' => array( 'integrated_edit_field50' ),
'sys_time' => array( 'integrated_edit_field51' ),
'usr_dep' => array( 'integrated_edit_field64' ),
'usr_cargo' => array( 'integrated_edit_field65' ),
'usr_extension' => array( 'integrated_edit_field67' ),
'usr_datebirth' => array( 'integrated_edit_field69' ),
'active' => array( 'integrated_edit_field74' ),
'groupid' => array( 'integrated_edit_field75' ),
'id_fk' => array( 'integrated_edit_field' ),
'phone' => array( 'integrated_edit_field2' ),
'usr_status' => array( 'integrated_edit_field6' ),
'usr_type_vinc' => array( 'integrated_edit_field8' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field67',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field69' ),
'section1' => array( 'integrated_edit_field27',
'integrated_edit_field29' ),
'section2' => array( 'integrated_edit_field65',
'integrated_edit_field51',
'integrated_edit_field64',
'integrated_edit_field50',
'integrated_edit_field74',
'integrated_edit_field',
'integrated_edit_field49',
'integrated_edit_field75',
'integrated_edit_field6',
'integrated_edit_field8' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'tabs' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field67' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field69' => 'section',
'integrated_edit_field27' => 'section1',
'integrated_edit_field29' => 'section1',
'integrated_edit_field65' => 'section2',
'integrated_edit_field51' => 'section2',
'integrated_edit_field64' => 'section2',
'integrated_edit_field50' => 'section2',
'integrated_edit_field74' => 'section2',
'integrated_edit_field' => 'section2',
'integrated_edit_field49' => 'section2',
'integrated_edit_field75' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field8' => 'section2' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field67' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field69' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field27' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field29' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field65' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field51' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field64' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field50' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field74' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field49' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'integrated_edit_field75' => array( 'location' => 'section2',
'cellId' => 'c7' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c8' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c9' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field27',
'integrated_edit_field29',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field67',
'integrated_edit_field69',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field8' ),
'tabs' => array( 'tabs' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c11' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field69' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field67' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c2' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field65' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field64' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field74' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field75' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field67' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field69' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field65' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field51' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field64' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field50' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field74' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field49' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field75' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c10' => array( 'model' => 'c1',
'items' => array(  ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'integrated_edit_field1' => array( 'field' => 'Username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'usr_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'usr_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'usr_lname',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'usr_personalid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'global_rol_almacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'global_rol_contratos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'sys_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'sys_time',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field64' => array( 'field' => 'usr_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field65' => array( 'field' => 'usr_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field67' => array( 'field' => 'usr_extension',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field69' => array( 'field' => 'usr_datebirth',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field74' => array( 'field' => 'active',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field75' => array( 'field' => 'groupid',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Información de usuario',
'type' => 0 ),
array( 'text' => 'Permisos módulos',
'type' => 0 ),
array( 'text' => '::',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field' => array( 'field' => 'id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'phone',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'usr_status',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'usr_type_vinc',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'pageWidth' => 'standard',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>