<?php
$dalTableep_compromisos = array();
$dalTableep_compromisos["CDP"] = array("type"=>200,"varname"=>"CDP", "name" => "CDP", "autoInc" => "0");
$dalTableep_compromisos["CID"] = array("type"=>3,"varname"=>"CID", "name" => "CID", "autoInc" => "1");
$dalTableep_compromisos["Compromisos"] = array("type"=>200,"varname"=>"Compromisos", "name" => "Compromisos", "autoInc" => "0");
$dalTableep_compromisos["Cuentas por Pagar"] = array("type"=>200,"varname"=>"Cuentas_por_Pagar", "name" => "Cuentas por Pagar", "autoInc" => "0");
$dalTableep_compromisos["Dependencia"] = array("type"=>200,"varname"=>"Dependencia", "name" => "Dependencia", "autoInc" => "0");
$dalTableep_compromisos["Dependencia Descripcion"] = array("type"=>200,"varname"=>"Dependencia_Descripcion", "name" => "Dependencia Descripcion", "autoInc" => "0");
$dalTableep_compromisos["Descripcion"] = array("type"=>200,"varname"=>"Descripcion", "name" => "Descripcion", "autoInc" => "0");
$dalTableep_compromisos["Entidad Descripcion"] = array("type"=>200,"varname"=>"Entidad_Descripcion", "name" => "Entidad Descripcion", "autoInc" => "0");
$dalTableep_compromisos["Entidad Nit"] = array("type"=>200,"varname"=>"Entidad_Nit", "name" => "Entidad Nit", "autoInc" => "0");
$dalTableep_compromisos["Estado"] = array("type"=>200,"varname"=>"Estado", "name" => "Estado", "autoInc" => "0");
$dalTableep_compromisos["Estado Cuenta"] = array("type"=>200,"varname"=>"Estado_Cuenta", "name" => "Estado Cuenta", "autoInc" => "0");
$dalTableep_compromisos["Fecha de Creacion"] = array("type"=>135,"varname"=>"Fecha_de_Creacion", "name" => "Fecha de Creacion", "autoInc" => "0");
$dalTableep_compromisos["Fecha de Registro"] = array("type"=>7,"varname"=>"Fecha_de_Registro", "name" => "Fecha de Registro", "autoInc" => "0");
$dalTableep_compromisos["Fecha Documento Soporte"] = array("type"=>7,"varname"=>"Fecha_Documento_Soporte", "name" => "Fecha Documento Soporte", "autoInc" => "0");
$dalTableep_compromisos["Fuente"] = array("type"=>200,"varname"=>"Fuente", "name" => "Fuente", "autoInc" => "0");
$dalTableep_compromisos["Identificacion"] = array("type"=>200,"varname"=>"Identificacion", "name" => "Identificacion", "autoInc" => "0");
$dalTableep_compromisos["Medio de Pago"] = array("type"=>200,"varname"=>"Medio_de_Pago", "name" => "Medio de Pago", "autoInc" => "0");
$dalTableep_compromisos["Nombre Razon Social"] = array("type"=>200,"varname"=>"Nombre_Razon_Social", "name" => "Nombre Razon Social", "autoInc" => "0");
$dalTableep_compromisos["Numero Cuenta"] = array("type"=>200,"varname"=>"Numero_Cuenta", "name" => "Numero Cuenta", "autoInc" => "0");
$dalTableep_compromisos["Numero Documento"] = array("type"=>200,"varname"=>"Numero_Documento", "name" => "Numero Documento", "autoInc" => "0");
$dalTableep_compromisos["Numero Documento Soporte"] = array("type"=>200,"varname"=>"Numero_Documento_Soporte", "name" => "Numero Documento Soporte", "autoInc" => "0");
$dalTableep_compromisos["Obligaciones"] = array("type"=>200,"varname"=>"Obligaciones", "name" => "Obligaciones", "autoInc" => "0");
$dalTableep_compromisos["Observaciones"] = array("type"=>200,"varname"=>"Observaciones", "name" => "Observaciones", "autoInc" => "0");
$dalTableep_compromisos["Ordenes de Pago"] = array("type"=>200,"varname"=>"Ordenes_de_Pago", "name" => "Ordenes de Pago", "autoInc" => "0");
$dalTableep_compromisos["Recurso"] = array("type"=>200,"varname"=>"Recurso", "name" => "Recurso", "autoInc" => "0");
$dalTableep_compromisos["Reintegros"] = array("type"=>200,"varname"=>"Reintegros", "name" => "Reintegros", "autoInc" => "0");
$dalTableep_compromisos["Rubro"] = array("type"=>200,"varname"=>"Rubro", "name" => "Rubro", "autoInc" => "0");
$dalTableep_compromisos["Saldo por Utilizar"] = array("type"=>5,"varname"=>"Saldo_por_Utilizar", "name" => "Saldo por Utilizar", "autoInc" => "0");
$dalTableep_compromisos["Situacion"] = array("type"=>200,"varname"=>"Situacion", "name" => "Situacion", "autoInc" => "0");
$dalTableep_compromisos["Solicitud CDP"] = array("type"=>200,"varname"=>"Solicitud_CDP", "name" => "Solicitud CDP", "autoInc" => "0");
$dalTableep_compromisos["Tipo Cuenta"] = array("type"=>200,"varname"=>"Tipo_Cuenta", "name" => "Tipo Cuenta", "autoInc" => "0");
$dalTableep_compromisos["Tipo Documento Soporte"] = array("type"=>200,"varname"=>"Tipo_Documento_Soporte", "name" => "Tipo Documento Soporte", "autoInc" => "0");
$dalTableep_compromisos["Tipo Identificacion"] = array("type"=>200,"varname"=>"Tipo_Identificacion", "name" => "Tipo Identificacion", "autoInc" => "0");
$dalTableep_compromisos["Valor Actual"] = array("type"=>5,"varname"=>"Valor_Actual", "name" => "Valor Actual", "autoInc" => "0");
$dalTableep_compromisos["Valor Inicial"] = array("type"=>5,"varname"=>"Valor_Inicial", "name" => "Valor Inicial", "autoInc" => "0");
$dalTableep_compromisos["Valor Operaciones"] = array("type"=>5,"varname"=>"Valor_Operaciones", "name" => "Valor Operaciones", "autoInc" => "0");
$dalTableep_compromisos["CID"]["key"]=true;

$dal_info["sep2_at_localhost__ep_compromisos"] = &$dalTableep_compromisos;
?>