<?php
$dalTableglobal_ejecucion = array();
$dalTableglobal_ejecucion["APR BLOQUEADA"] = array("type"=>5,"varname"=>"APR_BLOQUEADA", "name" => "APR BLOQUEADA", "autoInc" => "0");
$dalTableglobal_ejecucion["APR. ADICIONADA"] = array("type"=>5,"varname"=>"APR__ADICIONADA", "name" => "APR. ADICIONADA", "autoInc" => "0");
$dalTableglobal_ejecucion["APR. DISPONIBLE"] = array("type"=>5,"varname"=>"APR__DISPONIBLE", "name" => "APR. DISPONIBLE", "autoInc" => "0");
$dalTableglobal_ejecucion["APR. INICIAL"] = array("type"=>5,"varname"=>"APR__INICIAL", "name" => "APR. INICIAL", "autoInc" => "0");
$dalTableglobal_ejecucion["APR. REDUCIDA"] = array("type"=>5,"varname"=>"APR__REDUCIDA", "name" => "APR. REDUCIDA", "autoInc" => "0");
$dalTableglobal_ejecucion["APR. VIGENTE"] = array("type"=>5,"varname"=>"APR__VIGENTE", "name" => "APR. VIGENTE", "autoInc" => "0");
$dalTableglobal_ejecucion["CDP"] = array("type"=>5,"varname"=>"CDP", "name" => "CDP", "autoInc" => "0");
$dalTableglobal_ejecucion["CODIGO_BPIN"] = array("type"=>200,"varname"=>"CODIGO_BPIN", "name" => "CODIGO_BPIN", "autoInc" => "0");
$dalTableglobal_ejecucion["COMPROMISO"] = array("type"=>5,"varname"=>"COMPROMISO", "name" => "COMPROMISO", "autoInc" => "0");
$dalTableglobal_ejecucion["CTA"] = array("type"=>200,"varname"=>"CTA", "name" => "CTA", "autoInc" => "0");
$dalTableglobal_ejecucion["DEPENDENCIA_ID"] = array("type"=>3,"varname"=>"DEPENDENCIA_ID", "name" => "DEPENDENCIA_ID", "autoInc" => "0");
$dalTableglobal_ejecucion["DEPENDENCIA_SUP_ID"] = array("type"=>3,"varname"=>"DEPENDENCIA_SUP_ID", "name" => "DEPENDENCIA_SUP_ID", "autoInc" => "0");
$dalTableglobal_ejecucion["DESCRIPCION"] = array("type"=>200,"varname"=>"DESCRIPCION", "name" => "DESCRIPCION", "autoInc" => "0");
$dalTableglobal_ejecucion["FECHA_ACTUALIZACION"] = array("type"=>135,"varname"=>"FECHA_ACTUALIZACION", "name" => "FECHA_ACTUALIZACION", "autoInc" => "0");
$dalTableglobal_ejecucion["FECHA_CORTE"] = array("type"=>7,"varname"=>"FECHA_CORTE", "name" => "FECHA_CORTE", "autoInc" => "0");
$dalTableglobal_ejecucion["FICHA_BPIN"] = array("type"=>200,"varname"=>"FICHA_BPIN", "name" => "FICHA_BPIN", "autoInc" => "0");
$dalTableglobal_ejecucion["FUENTE"] = array("type"=>200,"varname"=>"FUENTE", "name" => "FUENTE", "autoInc" => "0");
$dalTableglobal_ejecucion["id_transac"] = array("type"=>3,"varname"=>"id_transac", "name" => "id_transac", "autoInc" => "1");
$dalTableglobal_ejecucion["ITEM"] = array("type"=>200,"varname"=>"ITEM", "name" => "ITEM", "autoInc" => "0");
$dalTableglobal_ejecucion["NOMBRE UEJ"] = array("type"=>200,"varname"=>"NOMBRE_UEJ", "name" => "NOMBRE UEJ", "autoInc" => "0");
$dalTableglobal_ejecucion["OBJ"] = array("type"=>200,"varname"=>"OBJ", "name" => "OBJ", "autoInc" => "0");
$dalTableglobal_ejecucion["OBLIGACION"] = array("type"=>5,"varname"=>"OBLIGACION", "name" => "OBLIGACION", "autoInc" => "0");
$dalTableglobal_ejecucion["ORD"] = array("type"=>200,"varname"=>"ORD", "name" => "ORD", "autoInc" => "0");
$dalTableglobal_ejecucion["ORDEN PAGO"] = array("type"=>5,"varname"=>"ORDEN_PAGO", "name" => "ORDEN PAGO", "autoInc" => "0");
$dalTableglobal_ejecucion["PAGOS"] = array("type"=>5,"varname"=>"PAGOS", "name" => "PAGOS", "autoInc" => "0");
$dalTableglobal_ejecucion["REC"] = array("type"=>200,"varname"=>"REC", "name" => "REC", "autoInc" => "0");
$dalTableglobal_ejecucion["RESPONSABLE_ID"] = array("type"=>3,"varname"=>"RESPONSABLE_ID", "name" => "RESPONSABLE_ID", "autoInc" => "0");
$dalTableglobal_ejecucion["RUBRO"] = array("type"=>200,"varname"=>"RUBRO", "name" => "RUBRO", "autoInc" => "0");
$dalTableglobal_ejecucion["SIT"] = array("type"=>200,"varname"=>"SIT", "name" => "SIT", "autoInc" => "0");
$dalTableglobal_ejecucion["SORORD"] = array("type"=>200,"varname"=>"SORORD", "name" => "SORORD", "autoInc" => "0");
$dalTableglobal_ejecucion["SUBCTA"] = array("type"=>200,"varname"=>"SUBCTA", "name" => "SUBCTA", "autoInc" => "0");
$dalTableglobal_ejecucion["SUBITEM"] = array("type"=>200,"varname"=>"SUBITEM", "name" => "SUBITEM", "autoInc" => "0");
$dalTableglobal_ejecucion["SUBITEM 2"] = array("type"=>200,"varname"=>"SUBITEM_2", "name" => "SUBITEM 2", "autoInc" => "0");
$dalTableglobal_ejecucion["TIPO"] = array("type"=>200,"varname"=>"TIPO", "name" => "TIPO", "autoInc" => "0");
$dalTableglobal_ejecucion["UEJ"] = array("type"=>200,"varname"=>"UEJ", "name" => "UEJ", "autoInc" => "0");
$dalTableglobal_ejecucion["UEJ_MIN"] = array("type"=>200,"varname"=>"UEJ_MIN", "name" => "UEJ_MIN", "autoInc" => "0");
$dalTableglobal_ejecucion["UEJ_S"] = array("type"=>200,"varname"=>"UEJ_S", "name" => "UEJ_S", "autoInc" => "0");
$dalTableglobal_ejecucion["USO_SN"] = array("type"=>16,"varname"=>"USO_SN", "name" => "USO_SN", "autoInc" => "0");
$dalTableglobal_ejecucion["VIGENCIA"] = array("type"=>2,"varname"=>"VIGENCIA", "name" => "VIGENCIA", "autoInc" => "0");
$dalTableglobal_ejecucion["id_transac"]["key"]=true;

$dal_info["sep2_at_localhost__global_ejecucion"] = &$dalTableglobal_ejecucion;
?>