<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_global_users_contratistas  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		// Actualiza el campo nombres full a traves de concat ws de los campos nombres y apellidos
$sql = DB::prepareSQL("UPDATE
dbusers.global_users
SET
dbusers.global_users.usr_nombresfull = CONCAT_WS(' ',dbusers.global_users.usr_name,dbusers.global_users.usr_lname);");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		// Actualiza el campo nombres full a traves de concat ws de los campos nombres y apellidos
$sql = DB::prepareSQL("UPDATE
dbusers.global_users
SET
dbusers.global_users.usr_nombresfull = CONCAT_WS(' ',dbusers.global_users.usr_name,dbusers.global_users.usr_lname);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
